apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: gcr.io/GOOGLE_PROJECT_ID/IMAGE_NAME:IMAGE_VERSION
        ports:
        - containerPort: 8080
