version: 2
jobs:
  deploy-job:
    docker:
      - image: google/cloud-sdk
        environment:
        - IMAGE_NAME: demo
        - IMAGE_VERSION: v1
        - CLUSTER_NAME: demo-cluster
        - DEPLOYMENT_NAME: demo
        - CONTAINER_TARGET_PORT: 8080
        - CONTAINER_PORT: 80
    steps:
      - checkout
      - run:
          name: Store GCP Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Configurate GCP
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - run:
          name: Submit image
          command: |
            gcloud container builds submit --tag=gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION} .
            gcloud container images list
      - run:
          name: Create pod
          command: | # gcloud container clusters create demo-cluster --num-nodes=2
            gcloud config set container/cluster ${CLUSTER_NAME}
            kubectl run ${DEPLOYMENT_NAME} --image=gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION} --port ${CONTAINER_TARGET_PORT}
            kubectl get pods
      - run:
          name: Run service
          command: |
            kubectl expose deployment ${DEPLOYMENT_NAME} --type=LoadBalancer --port ${CONTAINER_PORT} --target-port ${CONTAINER_TARGET_PORT}
            kubectl get service

workflows:
  version: 2
  build:
    jobs:
      - deploy-job
