type: google.api.Service
config_version: 3

name: worker.endpoints.GOOGLE_PROJECT_ID.cloud.goog

title: worker gRPC API
apis:
- name: Worker

usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true
