type: google.api.Service
config_version: 3

name: worker.endpoints.GOOGLE_PROJECT_ID.cloud.goog

title: worker gRPC API
apis:
- name: Worker

http:
  rules:
  - selector: Worker.GetWorkers
    get: /v1/workers
  - selector: Worker.GetWorker
    get: /v1/workers/{id}
  - selector: Worker.PostWorker
    post: /v1/workers
    body: worker

usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true
