apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: gcr.io/GOOGLE_PROJECT_ID/IMAGE_NAME:IMAGE_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 6565
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: review
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=CLOUD_SQL_INSTANCE_CONNECTION_NAME=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: grpc-webproxy
          image: jfyne/docker-grpcwebproxy
          ports:
            - containerPort: 8080
          command: ["/grpcwebproxy",
                    "--backend_addr=127.0.0.1:6565",
                    "--run_tls_server=false"]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials

---

apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  loadBalancerIP: WORKER_SERVICE_IP
